name: danhwang
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51409
title: Dan Hwang
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2bcc3'
    - '#101012'
    - '#9e9c9f'
    - '#595b5a'
    - '#b0623e'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
