analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8425454709213227
  lightness: 0.4350105719640851
  brandStrength: 0.9964158
  brandColors:
    - '#181F27'
    - '#BECEE0'
    - '#415D92'
    - '#879BBC'
    - '#C8B540'
  rhythmicContrast: 0.9379572561010718
typography_spectrum: 0.001792115
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7258065
favicon: null
name: danhwang
