name: danhwang
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20701
title: Dan Hwang
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#cd1c22'
    - '#424242'
    - '#b5b5b5'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
